/** ISO 4217 codes that use 0 decimal places in cash amounts. */
export const ZERO_DECIMAL_CURRENCIES = new Set([
  "BIF",
  "CLP",
  "COP",
  "DJF",
  "GNF",
  "ISK",
  "JPY",
  "KMF",
  "KRW",
  "PYG",
  "RWF",
  "UGX",
  "VND",
  "VUV",
  "XAF",
  "XOF",
  "XPF",
]);

/** ISO 4217 codes that use 3 decimal places. */
export const THREE_DECIMAL_CURRENCIES = new Set([
  "BHD",
  "IQD",
  "JOD",
  "KWD",
  "LYD",
  "OMR",
  "TND",
]);

export type CurrencyLabel = {
  name: string;
  short: string;
};

export const CURRENCY_LABELS: Record<string, CurrencyLabel> = {
  AED: { name: "Dírhams de los EAU", short: "dírhams" },
  AFN: { name: "Afganis", short: "afganis" },
  ALL: { name: "Leks", short: "leks" },
  AMD: { name: "Drams", short: "drams" },
  ANG: { name: "Florines antillanos", short: "florines" },
  AOA: { name: "Kwanzas", short: "kwanzas" },
  ARS: { name: "Pesos argentinos", short: "pesos" },
  AUD: { name: "Dólares australianos", short: "dólares" },
  AWG: { name: "Florines de Aruba", short: "florines" },
  AZN: { name: "Manat azerbaiyanos", short: "manat" },
  BAM: { name: "Marcos convertibles", short: "marcos" },
  BBD: { name: "Dólares de Barbados", short: "dólares" },
  BDT: { name: "Takas", short: "takas" },
  BGN: { name: "Levas", short: "levas" },
  BHD: { name: "Dinares bahreiníes", short: "dinares" },
  BIF: { name: "Francos burundeses", short: "francos" },
  BMD: { name: "Dólares de Bermudas", short: "dólares" },
  BND: { name: "Dólares de Brunéi", short: "dólares" },
  BOB: { name: "Bolivianos", short: "bolivianos" },
  BRL: { name: "Reales", short: "reales" },
  BSD: { name: "Dólares bahameños", short: "dólares" },
  BTN: { name: "Ngultrums", short: "ngultrums" },
  BWP: { name: "Pulas", short: "pulas" },
  BYN: { name: "Rublos bielorrusos", short: "rublos" },
  BZD: { name: "Dólares beliceños", short: "dólares" },
  CAD: { name: "Dólares canadienses", short: "dólares" },
  CDF: { name: "Francos congoleños", short: "francos" },
  CHF: { name: "Francos suizos", short: "francos" },
  CLP: { name: "Pesos chilenos", short: "pesos" },
  CNY: { name: "Yuanes", short: "yuanes" },
  COP: { name: "Pesos colombianos", short: "pesos" },
  CRC: { name: "Colones", short: "colones" },
  CUP: { name: "Pesos cubanos", short: "pesos" },
  CVE: { name: "Escudos caboverdianos", short: "escudos" },
  CZK: { name: "Coronas checas", short: "coronas" },
  DJF: { name: "Francos de Yibuti", short: "francos" },
  DKK: { name: "Coronas danesas", short: "coronas" },
  DOP: { name: "Pesos dominicanos", short: "pesos" },
  DZD: { name: "Dinares argelinos", short: "dinares" },
  EGP: { name: "Libras egipcias", short: "libras" },
  ERN: { name: "Nakfas", short: "nakfas" },
  ETB: { name: "Birs", short: "birs" },
  EUR: { name: "Euros", short: "euros" },
  FJD: { name: "Dólares fiyianos", short: "dólares" },
  FKP: { name: "Libras malvinenses", short: "libras" },
  FOK: { name: "Coronas feroesas", short: "coronas" },
  GBP: { name: "Libras esterlinas", short: "libras" },
  GEL: { name: "Laris", short: "laris" },
  GGP: { name: "Libras de Guernsey", short: "libras" },
  GHS: { name: "Cedis", short: "cedis" },
  GIP: { name: "Libras gibraltareñas", short: "libras" },
  GMD: { name: "Dalasis", short: "dalasis" },
  GNF: { name: "Francos guineanos", short: "francos" },
  GTQ: { name: "Quetzales", short: "quetzales" },
  GYD: { name: "Dólares guyaneses", short: "dólares" },
  HKD: { name: "Dólares de Hong Kong", short: "dólares" },
  HNL: { name: "Lempiras", short: "lempiras" },
  HRK: { name: "Kunas", short: "kunas" },
  HTG: { name: "Gurdes", short: "gurdes" },
  HUF: { name: "Florines húngaros", short: "florines" },
  IDR: { name: "Rupias indonesias", short: "rupias" },
  ILS: { name: "Nuevos shéquels", short: "shéquels" },
  IMP: { name: "Libras de Man", short: "libras" },
  INR: { name: "Rupias indias", short: "rupias" },
  IQD: { name: "Dinares iraquíes", short: "dinares" },
  IRR: { name: "Riales iraníes", short: "riales" },
  ISK: { name: "Coronas islandesas", short: "coronas" },
  JEP: { name: "Libras de Jersey", short: "libras" },
  JMD: { name: "Dólares jamaiquinos", short: "dólares" },
  JOD: { name: "Dinares jordanos", short: "dinares" },
  JPY: { name: "Yenes", short: "yenes" },
  KES: { name: "Chelines kenianos", short: "chelines" },
  KGS: { name: "Soms", short: "soms" },
  KHR: { name: "Rieles", short: "rieles" },
  KID: { name: "Dólares de Kiribati", short: "dólares" },
  KMF: { name: "Francos comorenses", short: "francos" },
  KPW: { name: "Wones norcoreanos", short: "wones" },
  KRW: { name: "Wones", short: "wones" },
  KWD: { name: "Dinares kuwaitíes", short: "dinares" },
  KYD: { name: "Dólares de Caimán", short: "dólares" },
  KZT: { name: "Tenges", short: "tenges" },
  LAK: { name: "Kips", short: "kips" },
  LBP: { name: "Libras libanesas", short: "libras" },
  LKR: { name: "Rupias de Sri Lanka", short: "rupias" },
  LRD: { name: "Dólares liberianos", short: "dólares" },
  LSL: { name: "Lotis", short: "lotis" },
  LYD: { name: "Dinares libios", short: "dinares" },
  MAD: { name: "Dírhams marroquíes", short: "dírhams" },
  MDL: { name: "Leus moldavos", short: "leus" },
  MGA: { name: "Ariarys", short: "ariarys" },
  MKD: { name: "Denares", short: "denares" },
  MMK: { name: "Kyats", short: "kyats" },
  MNT: { name: "Tugriks", short: "tugriks" },
  MOP: { name: "Patacas", short: "patacas" },
  MRU: { name: "Uguiyas", short: "uguiyas" },
  MUR: { name: "Rupias mauricianas", short: "rupias" },
  MVR: { name: "Rufiyas", short: "rufiyas" },
  MWK: { name: "Kwachas malauíes", short: "kwachas" },
  MXN: { name: "Pesos mexicanos", short: "pesos" },
  MYR: { name: "Ringgits", short: "ringgits" },
  MZN: { name: "Meticales", short: "meticales" },
  NAD: { name: "Dólares namibios", short: "dólares" },
  NGN: { name: "Nairas", short: "nairas" },
  NIO: { name: "Córdobas", short: "córdobas" },
  NOK: { name: "Coronas noruegas", short: "coronas" },
  NPR: { name: "Rupias nepalíes", short: "rupias" },
  NZD: { name: "Dólares neozelandeses", short: "dólares" },
  OMR: { name: "Riales omaníes", short: "riales" },
  PAB: { name: "Balboas", short: "balboas" },
  PEN: { name: "Soles", short: "soles" },
  PGK: { name: "Kinas", short: "kinas" },
  PHP: { name: "Pesos filipinos", short: "pesos" },
  PKR: { name: "Rupias pakistaníes", short: "rupias" },
  PLN: { name: "Zlotys", short: "zlotys" },
  PYG: { name: "Guaraníes", short: "guaraníes" },
  QAR: { name: "Riyales cataríes", short: "riyales" },
  RON: { name: "Leus rumanos", short: "leus" },
  RSD: { name: "Dinares serbios", short: "dinares" },
  RUB: { name: "Rublos", short: "rublos" },
  RWF: { name: "Francos ruandeses", short: "francos" },
  SAR: { name: "Riyales saudíes", short: "riyales" },
  SBD: { name: "Dólares de Salomón", short: "dólares" },
  SCR: { name: "Rupias de Seychelles", short: "rupias" },
  SDG: { name: "Libras sudanesas", short: "libras" },
  SEK: { name: "Coronas suecas", short: "coronas" },
  SGD: { name: "Dólares de Singapur", short: "dólares" },
  SHP: { name: "Libras de Santa Elena", short: "libras" },
  SLE: { name: "Leones", short: "leones" },
  SLL: { name: "Leones", short: "leones" },
  SOS: { name: "Chelines somalíes", short: "chelines" },
  SRD: { name: "Dólares surinameses", short: "dólares" },
  SSP: { name: "Libras sursudanesas", short: "libras" },
  STN: { name: "Dobras", short: "dobras" },
  SYP: { name: "Libras sirias", short: "libras" },
  SZL: { name: "Lilangenis", short: "lilangenis" },
  THB: { name: "Bahts", short: "bahts" },
  TJS: { name: "Somoni", short: "somoni" },
  TMT: { name: "Manat turcomanos", short: "manat" },
  TND: { name: "Dinares tunecinos", short: "dinares" },
  TOP: { name: "Paangas", short: "paangas" },
  TRY: { name: "Liras turcas", short: "liras" },
  TTD: { name: "Dólares de Trinidad", short: "dólares" },
  TVD: { name: "Dólares de Tuvalu", short: "dólares" },
  TWD: { name: "Dólares taiwaneses", short: "dólares" },
  TZS: { name: "Chelines tanzanos", short: "chelines" },
  UAH: { name: "Grivnas", short: "grivnas" },
  UGX: { name: "Chelines ugandeses", short: "chelines" },
  USD: { name: "Dólares", short: "dólares" },
  UYU: { name: "Pesos uruguayos", short: "pesos" },
  UZS: { name: "Soms uzbekos", short: "soms" },
  VES: { name: "Bolívares", short: "bolívares" },
  VND: { name: "Dongs", short: "dongs" },
  VUV: { name: "Vatus", short: "vatus" },
  WST: { name: "Talas", short: "talas" },
  XAF: { name: "Francos CFA (BEAC)", short: "francos" },
  XCD: { name: "Dólares del Caribe Oriental", short: "dólares" },
  XOF: { name: "Francos CFA (BCEAO)", short: "francos" },
  XPF: { name: "Francos CFP", short: "francos" },
  YER: { name: "Riales yemeníes", short: "riales" },
  ZAR: { name: "Rands", short: "rands" },
  ZMW: { name: "Kwachas zambianos", short: "kwachas" },
  ZWG: { name: "ZiG", short: "ZiG" },
  ZWL: { name: "Dólares zimbabuenses", short: "dólares" },
};

export function currencyLabel(code: string): CurrencyLabel {
  return (
    CURRENCY_LABELS[code] ?? {
      name: code,
      short: code.toLowerCase(),
    }
  );
}

export function currencyFractionDigits(currency: string): number {
  if (ZERO_DECIMAL_CURRENCIES.has(currency)) return 0;
  if (THREE_DECIMAL_CURRENCIES.has(currency)) return 3;
  return 2;
}
